language: python
python:
    - 2.7
    - 3.4
    - 3.5
env:
  - TRAVIS_NODE_VERSION="8"
install:
    # Clear out whatever version of NVM Travis has.
    # Grab NVM and Checkout the latest stable tag.
    # Install the desired version of Node
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install
    - pip install -U pip setuptools
    - npm run install-pytools
script:
    - npm run cibuild
    - npm run build
    - python setup.py install
