# Generated by Django 3.2.4 on 2021-06-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import draalcore.models.base_model
import draalcore.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted'), ('Pending', 'Pending')], default='Active', help_text='Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text='Latest modification timestamp.')),
                ('activation_key', models.CharField(help_text='Account activation key', max_length=40)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Activated', 'Activated'), ('Expired', 'Expired')], default='Active', help_text='Account status', max_length=24)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text='User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='account_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'useraccount',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
        ),
    ]
