# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draalcore.auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountprofile',
            name='account_status',
            field=models.CharField(choices=[(b'Active', b'Active'), (b'Activated', b'Activated'), (b'Deleted', b'Deleted'), (b'Expired', b'Expired')], default=b'Active', help_text=b'Account status', max_length=24),
        ),
    ]
