# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-31 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import draalcore.models.base_model
import draalcore.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[(b'Active', 'Active'), (b'Deleted', 'Deleted'), (b'Pending', 'Pending')], default=b'Active', help_text=b'Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text=b'Latest modification timestamp.')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text=b'User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testmodel',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[(b'Active', 'Active'), (b'Deleted', 'Deleted'), (b'Pending', 'Pending')], default=b'Active', help_text=b'Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text=b'Latest modification timestamp.')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('comments', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('free_text', draalcore.models.fields.AppModelTextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, default=-1, null=True)),
                ('meta', draalcore.models.fields.AppModelForeignObjectKey(blank=True, help_text=b'Metadata information', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_models.TestModel')),
                ('model1', draalcore.models.fields.AppModelForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model1', to='test_models.TestModel')),
                ('model2', draalcore.models.fields.AppModelForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model2', to='test_models.TestModel')),
                ('model3', draalcore.models.fields.AppModelManyToManyField(blank=True, null=True, related_name='model3', to='test_models.TestModel')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text=b'User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testmodel2',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'testmodel3',
            },
        ),
        migrations.CreateModel(
            name='TestModel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[(b'Active', 'Active'), (b'Deleted', 'Deleted'), (b'Pending', 'Pending')], default=b'Active', help_text=b'Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text=b'Latest modification timestamp.')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text=b'User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testmodel4',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[(b'Active', 'Active'), (b'Deleted', 'Deleted'), (b'Pending', 'Pending')], default=b'Active', help_text=b'Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text=b'Latest modification timestamp.')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text=b'User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testmodel5',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', draalcore.models.fields.AppModelCharField(choices=[(b'Active', 'Active'), (b'Deleted', 'Deleted'), (b'Pending', 'Pending')], default=b'Active', help_text=b'Item activity status', max_length=24)),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text=b'Latest modification timestamp.')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, help_text=b'User who modified the data.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testmodel6',
            },
            bases=(draalcore.models.base_model.EventHandlingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestModelBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', draalcore.models.fields.AppModelCharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'testmodelbasemodel',
            },
        ),
    ]
